<?php
include dirname(dirname(__DIR__)) . '/inc/koneksi.php';
include_once dirname(dirname(__DIR__)) . '/inc/activity_log.php';

// Proses Backup
if (isset($_POST['backup'])) {
    $db_name = 'db_tabsis';
    $backup_dir = dirname(dirname(__DIR__)) . '/backup/';
    
    // Buat folder backup jika belum ada
    if (!file_exists($backup_dir)) {
        mkdir($backup_dir, 0777, true);
    }
    
    $filename = 'backup_' . $db_name . '_' . date('Y-m-d_His') . '.sql';
    $filepath = $backup_dir . $filename;
    
    // Koneksi database
    $host = 'localhost';
    $user = 'root';
    $pass = '';
    
    // Command untuk backup menggunakan mysqldump
    $command = "mysqldump --host=$host --user=$user --password=$pass $db_name > " . escapeshellarg($filepath) . " 2>&1";
    
    // Jika di Windows (Laragon)
    if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') {
        // Cari path MySQL di Laragon
        $mysql_paths = [
            'C:\\laragon\\bin\\mysql\\mysql-8.0.30\\bin\\mysqldump.exe',
            'C:\\laragon\\bin\\mysql\\mysql-8.0.24\\bin\\mysqldump.exe',
            'C:\\xampp\\mysql\\bin\\mysqldump.exe',
            'C:\\wamp64\\bin\\mysql\\mysql8.0.27\\bin\\mysqldump.exe',
        ];
        
        $mysqldump = '';
        foreach ($mysql_paths as $path) {
            if (file_exists($path)) {
                $mysqldump = $path;
                break;
            }
        }
        
        if (empty($mysqldump)) {
            // Fallback: coba dari PATH
            $mysqldump = 'mysqldump';
        }
        
        $command = "\"$mysqldump\" --host=$host --user=$user --password=$pass $db_name > " . escapeshellarg($filepath) . " 2>&1";
    }
    
    exec($command, $output, $return_var);
    
    if ($return_var === 0 && file_exists($filepath) && filesize($filepath) > 0) {
        $file_size = filesize($filepath);
        $file_size_mb = round($file_size / 1024 / 1024, 2);
        
            // Log aktivitas
            if (function_exists('logActivity')) {
                logActivity($koneksi, 'BACKUP', 'database', 'Membuat backup database: ' . $filename . ' (' . $file_size_mb . ' MB)');
            }
            
            echo "<script>
            Swal.fire({
                title: 'Backup Berhasil!',
                html: 'Database berhasil di-backup.<br><br><strong>File:</strong> $filename<br><strong>Ukuran:</strong> $file_size_mb MB<br><strong>Lokasi:</strong> backup/$filename',
                icon: 'success',
                confirmButtonText: 'OK',
                timer: 3000,
                timerProgressBar: true,
                width: '500px'
            });
            </script>";
    } else {
        // Fallback: Backup manual menggunakan PHP (lebih reliable)
        $backup_content = "-- Backup Database: $db_name\n";
        $backup_content .= "-- Tanggal: " . date('Y-m-d H:i:s') . "\n";
        $backup_content .= "-- Generated by PHP Backup Script\n\n";
        $backup_content .= "SET SQL_MODE = \"NO_AUTO_VALUE_ON_ZERO\";\n";
        $backup_content .= "SET time_zone = \"+00:00\";\n";
        $backup_content .= "SET FOREIGN_KEY_CHECKS = 0;\n\n";
        $backup_content .= "CREATE DATABASE IF NOT EXISTS `$db_name` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;\n";
        $backup_content .= "USE `$db_name`;\n\n";
        
        // Get all tables
        $tables = [];
        $result = mysqli_query($koneksi, "SHOW TABLES");
        if ($result) {
            while ($row = mysqli_fetch_row($result)) {
                $tables[] = $row[0];
            }
        }
        
        $total_rows = 0;
        $table_stats = [];
        
        foreach ($tables as $table) {
            $backup_content .= "\n-- --------------------------------------------------------\n";
            $backup_content .= "-- Table structure for table `$table`\n";
            $backup_content .= "-- --------------------------------------------------------\n\n";
            $backup_content .= "DROP TABLE IF EXISTS `$table`;\n";
            
            $create_table = mysqli_query($koneksi, "SHOW CREATE TABLE `$table`");
            if ($create_table && $create_row = mysqli_fetch_row($create_table)) {
                $backup_content .= $create_row[1] . ";\n\n";
            }
            
            // Get table data
            $backup_content .= "-- Dumping data for table `$table`\n\n";
            
            // Count total rows first
            $count_result = mysqli_query($koneksi, "SELECT COUNT(*) as total FROM `$table`");
            $count_data = mysqli_fetch_assoc($count_result);
            $table_row_count = $count_data['total'];
            
            $data_result = mysqli_query($koneksi, "SELECT * FROM `$table`");
            
            if ($data_result && mysqli_num_rows($data_result) > 0) {
                // Get column names
                $columns = [];
                $fields = mysqli_fetch_fields($data_result);
                foreach ($fields as $field) {
                    $columns[] = "`" . $field->name . "`";
                }
                $column_list = implode(", ", $columns);
                
                // Reset result pointer
                mysqli_data_seek($data_result, 0);
                
                $backup_content .= "INSERT INTO `$table` ($column_list) VALUES\n";
                $values = [];
                $row_count = 0;
                
                while ($data_row = mysqli_fetch_assoc($data_result)) {
                    $row_values = [];
                    foreach ($columns as $col) {
                        $col_name = trim($col, '`');
                        $value = isset($data_row[$col_name]) ? $data_row[$col_name] : null;
                        
                        if ($value === null) {
                            $row_values[] = 'NULL';
                        } else {
                            // Escape properly - handle special characters
                            $escaped = mysqli_real_escape_string($koneksi, $value);
                            // Handle binary data or special characters
                            $row_values[] = "'" . str_replace(array("\r", "\n", "\t"), array("\\r", "\\n", "\\t"), $escaped) . "'";
                        }
                    }
                    $values[] = "(" . implode(", ", $row_values) . ")";
                    $row_count++;
                }
                
                if (!empty($values)) {
                    // Split large inserts into chunks for better performance
                    $chunk_size = 100;
                    $chunks = array_chunk($values, $chunk_size);
                    
                    foreach ($chunks as $chunk_index => $chunk) {
                        if ($chunk_index > 0) {
                            $backup_content .= "INSERT INTO `$table` ($column_list) VALUES\n";
                        }
                        $backup_content .= implode(",\n", $chunk);
                        if ($chunk_index < count($chunks) - 1) {
                            $backup_content .= ";\n\n";
                        } else {
                            $backup_content .= ";\n\n";
                        }
                    }
                    
                    $total_rows += $row_count;
                    $table_stats[$table] = $row_count;
                } else {
                    $backup_content .= "-- No data in table `$table`\n\n";
                    $table_stats[$table] = 0;
                }
            } else {
                $backup_content .= "-- No data in table `$table`\n\n";
                $table_stats[$table] = 0;
            }
        }
        
        $backup_content .= "\nSET FOREIGN_KEY_CHECKS = 1;\n";
        
        // Write to file
        $written = file_put_contents($filepath, $backup_content);
        
        if ($written !== false && file_exists($filepath) && filesize($filepath) > 0) {
            $file_size = filesize($filepath);
            $file_size_kb = round($file_size / 1024, 2);
            $file_size_mb = round($file_size / 1024 / 1024, 2);
            
            $size_display = $file_size_mb >= 1 ? $file_size_mb . ' MB' : $file_size_kb . ' KB';
            
            // Build table stats detail
            $stats_detail = '';
            foreach ($table_stats as $tbl => $count) {
                $stats_detail .= '<br>- ' . $tbl . ': ' . $count . ' baris';
            }
            
            // Log aktivitas
            if (function_exists('logActivity')) {
                logActivity($koneksi, 'BACKUP', 'database', 'Membuat backup database: ' . $filename . ' (' . $size_display . ', ' . count($tables) . ' tabel, ' . $total_rows . ' baris)');
            }
            
            echo "<script>
            Swal.fire({
                title: 'Backup Berhasil!',
                html: 'Database berhasil di-backup.<br><br><strong>File:</strong> $filename<br><strong>Ukuran:</strong> $size_display<br><strong>Total Tabel:</strong> " . count($tables) . "<br><strong>Total Data:</strong> $total_rows baris<br><strong>Detail per Tabel:</strong>$stats_detail<br><br><strong>Lokasi:</strong> backup/$filename',
                icon: 'success',
                confirmButtonText: 'OK',
                timer: 4000,
                timerProgressBar: true,
                width: '600px'
            });
            </script>";
        } else {
            $error_msg = 'Gagal membuat file backup.';
            if (!is_writable($backup_dir)) {
                $error_msg .= ' Folder backup tidak dapat ditulis.';
            }
            
            echo "<script>
            Swal.fire({
                title: 'Backup Gagal!',
                text: '$error_msg',
                icon: 'error',
                confirmButtonText: 'OK'
            });
            </script>";
        }
    }
}

// Proses Hapus Backup
if (isset($_GET['hapus_backup'])) {
    $filename = basename($_GET['hapus_backup']);
    $backup_dir = dirname(dirname(__DIR__)) . '/backup/';
    $filepath = $backup_dir . $filename;
    
    // Validasi: hanya file backup yang bisa dihapus
    if (strpos($filename, 'backup_') === 0 && pathinfo($filename, PATHINFO_EXTENSION) === 'sql') {
        if (file_exists($filepath)) {
            if (unlink($filepath)) {
                // Log aktivitas
                if (function_exists('logActivity')) {
                    logActivity($koneksi, 'DELETE', 'backup', 'Menghapus file backup: ' . $filename);
                }
                
                echo "<script>
                Swal.fire({
                    title: '<i class=\"fa fa-check-circle\" style=\"color: #28a745;\"></i> File Berhasil Dihapus!',
                    html: '<div style=\"text-align: center; padding: 10px;\">' +
                          '<p style=\"font-size: 16px; margin-bottom: 15px;\">File backup telah berhasil dihapus:</p>' +
                          '<div style=\"background-color: #f8f9fa; padding: 15px; border-radius: 5px; display: inline-block; margin-bottom: 15px;\">' +
                          '<p style=\"margin: 0; font-weight: bold; color: #495057;\"><i class=\"fa fa-file-code-o\"></i> ' + " . json_encode($filename) . " + '</p>' +
                          '</div>' +
                          '</div>',
                    icon: 'success',
                    confirmButtonColor: '#28a745',
                    confirmButtonText: '<i class=\"fa fa-check\"></i> OK',
                    timer: 3000,
                    timerProgressBar: true
                }).then((result) => {
                    window.location = 'index.php?page=MyApp/backup_restore';
                });
                </script>";
            } else {
                echo "<script>
                Swal.fire({
                    title: 'Gagal Menghapus',
                    text: 'Gagal menghapus file backup',
                    icon: 'error',
                    confirmButtonText: 'OK'
                });
                </script>";
            }
        } else {
            echo "<script>
            Swal.fire({
                title: 'File Tidak Ditemukan',
                text: 'File backup tidak ditemukan',
                icon: 'error',
                confirmButtonText: 'OK'
            });
            </script>";
        }
    } else {
        echo "<script>
        Swal.fire({
            title: 'Akses Ditolak',
            text: 'File tidak valid untuk dihapus',
            icon: 'error',
            confirmButtonText: 'OK'
        });
        </script>";
    }
}

// Proses Restore
if (isset($_POST['restore'])) {
    if (isset($_FILES['file_restore']) && $_FILES['file_restore']['error'] == 0) {
        $file_tmp = $_FILES['file_restore']['tmp_name'];
        $file_name = $_FILES['file_restore']['name'];
        $file_ext = strtolower(pathinfo($file_name, PATHINFO_EXTENSION));
        
        if ($file_ext !== 'sql') {
            echo "<script>
            Swal.fire({
                title: 'Format File Tidak Valid',
                text: 'Hanya file SQL yang diperbolehkan',
                icon: 'error',
                confirmButtonText: 'OK'
            });
            </script>";
        } else {
            // Baca file SQL
            $sql_content = file_get_contents($file_tmp);
            
            if (empty($sql_content)) {
                echo "<script>
                Swal.fire({
                    title: 'File Kosong',
                    text: 'File SQL yang diupload kosong atau tidak valid',
                    icon: 'error',
                    confirmButtonText: 'OK'
                });
                </script>";
            } else {
                // Set timeout untuk query besar
                set_time_limit(300);
                ini_set('max_execution_time', 300);
                ini_set('memory_limit', '256M');
                
                // Disable foreign key checks
                mysqli_query($koneksi, "SET FOREIGN_KEY_CHECKS = 0");
                mysqli_query($koneksi, "SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO'");
                
                $success_count = 0;
                $error_count = 0;
                $errors = [];
                
                // Baca file baris per baris dan eksekusi query
                $handle = fopen($file_tmp, 'r');
                if ($handle) {
                    $current_query = '';
                    
                    while (($line = fgets($handle)) !== false) {
                        $line = trim($line);
                        
                        // Skip komentar dan baris kosong
                        if (empty($line) || 
                            strpos($line, '--') === 0 || 
                            strpos($line, '/*') === 0 ||
                            strpos($line, '*/') !== false) {
                            continue;
                        }
                        
                        // Hapus komentar di akhir baris
                        if (strpos($line, '--') !== false) {
                            $line = substr($line, 0, strpos($line, '--'));
                            $line = trim($line);
                        }
                        
                        // Tambahkan baris ke query
                        $current_query .= $line . ' ';
                        
                        // Jika baris berakhir dengan semicolon, eksekusi query
                        if (substr(rtrim($line), -1) === ';') {
                            $query = trim($current_query);
                            $current_query = '';
                            
                            // Skip query kosong atau terlalu pendek
                            if (empty($query) || strlen($query) < 5) {
                                continue;
                            }
                            
                            // Skip CREATE DATABASE dan USE (sudah di database yang benar)
                            if (preg_match('/^(CREATE DATABASE|USE|SET)/i', trim($query))) {
                                // Execute SET commands
                                if (preg_match('/^SET/i', trim($query))) {
                                    mysqli_query($koneksi, $query);
                                }
                                continue;
                            }
                            
                            // Eksekusi query
                            if (mysqli_query($koneksi, $query)) {
                                $success_count++;
                            } else {
                                $error = mysqli_error($koneksi);
                                // Skip error yang tidak kritis
                                if (strpos($error, 'Duplicate entry') === false && 
                                    strpos($error, 'already exists') === false &&
                                    strpos($error, 'Unknown database') === false &&
                                    strpos($error, 'Table') === false) {
                                    $error_count++;
                                    if (count($errors) < 10) {
                                        $errors[] = substr($error, 0, 100);
                                    }
                                } else {
                                    $success_count++; // Count as success
                                }
                            }
                        }
                    }
                    fclose($handle);
                } else {
                    $error_count++;
                    $errors[] = 'Gagal membaca file SQL';
                }
                
                // Enable foreign key checks
                mysqli_query($koneksi, "SET FOREIGN_KEY_CHECKS = 1");
                
                // Count data yang ter-restore
                $affected_rows = 0;
                $tables_restored = [];
                $result = mysqli_query($koneksi, "SHOW TABLES");
                if ($result) {
                    while ($row = mysqli_fetch_row($result)) {
                        $table = $row[0];
                        $count_result = mysqli_query($koneksi, "SELECT COUNT(*) as total FROM `$table`");
                        if ($count_result) {
                            $count_data = mysqli_fetch_assoc($count_result);
                            $tables_restored[$table] = $count_data['total'];
                            $affected_rows += $count_data['total'];
                        }
                    }
                }
                
                if ($error_count == 0) {
                    $tables_detail = '';
                    foreach ($tables_restored as $tbl => $count) {
                        $tables_detail .= '<br>- ' . $tbl . ': ' . $count . ' baris';
                    }
                    
                    // Log aktivitas
                    if (function_exists('logActivity')) {
                        logActivity($koneksi, 'RESTORE', 'database', 'Restore database dari file: ' . $file_name . ' (' . $success_count . ' query berhasil, ' . $affected_rows . ' baris)');
                    }
                    
                    echo "<script>
                    Swal.fire({
                        title: 'Restore Berhasil!',
                        html: 'Database berhasil di-restore.<br><br><strong>Query berhasil:</strong> $success_count<br><strong>Total Data:</strong> $affected_rows baris<br><strong>Detail per Tabel:</strong>$tables_detail',
                        icon: 'success',
                        confirmButtonText: 'OK',
                        timer: 4000,
                        timerProgressBar: true,
                        width: '600px'
                    }).then((result) => {
                        window.location = 'index.php?page=MyApp/backup_restore';
                    });
                    
                    // Auto redirect setelah 4 detik jika tidak diklik
                    setTimeout(function(){
                        window.location = 'index.php?page=MyApp/backup_restore';
                    }, 4000);
                    </script>";
                } else {
                    $error_msg = implode('<br>', array_slice($errors, 0, 10));
                    if (count($errors) > 10) {
                        $error_msg .= '<br>... dan ' . (count($errors) - 10) . ' error lainnya';
                    }
                    
                    $tables_detail = '';
                    if (!empty($tables_restored)) {
                        foreach ($tables_restored as $tbl => $count) {
                            $tables_detail .= '<br>- ' . $tbl . ': ' . $count . ' baris';
                        }
                    }
                    
                    echo "<script>
                    Swal.fire({
                        title: 'Restore dengan Error',
                        html: 'Database di-restore dengan beberapa error.<br><br><strong>Query berhasil:</strong> $success_count<br><strong>Query gagal:</strong> $error_count<br><strong>Data ter-restore:</strong> $affected_rows baris$tables_detail<br><br><strong>Detail Error:</strong><br>$error_msg',
                        icon: 'warning',
                        confirmButtonText: 'OK',
                        width: '700px'
                    });
                    </script>";
                }
            }
        }
    } else {
        echo "<script>
        Swal.fire({
            title: 'File Tidak Ditemukan',
            text: 'Silakan pilih file SQL untuk di-restore',
            icon: 'error',
            confirmButtonText: 'OK'
        });
        </script>";
    }
}
?>

<section class="content-header">
    <h1>
        Backup & Restore Database
        <small>Kelola backup dan restore database</small>
    </h1>
</section>

<section class="content">
    <div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
        <!-- Backup Card -->
        <div class="rounded-2xl bg-white shadow-sm h-full flex flex-col">
            <div class="border-b border-slate-100 px-6 py-4">
                <h3 class="text-lg font-semibold text-slate-900 flex items-center gap-2">
                    <i class="fa-solid fa-download text-indigo-500"></i>
                    <span>Backup Database</span>
                </h3>
            </div>
            <form method="POST" action="" class="flex-1 flex flex-col">
                <div class="p-6 space-y-4 flex-1">
                    <div class="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-900">
                        <div class="flex items-start gap-3">
                            <i class="fa-solid fa-circle-info text-lg text-blue-600"></i>
                            <div>
                                <strong class="text-blue-900">Informasi:</strong>
                                <span> Backup akan membuat file SQL dari seluruh database. File akan disimpan di folder </span>
                                <code class="bg-blue-100 px-1 py-0.5 rounded font-mono text-xs font-bold text-blue-900">backup/</code>
                            </div>
                        </div>
                    </div>
                    
                    <div class="space-y-1.5">
                        <label class="text-sm font-medium text-slate-700">Nama Database</label>
                        <input type="text" class="block w-full rounded-xl border border-slate-300 bg-slate-50 px-4 py-2.5 text-sm text-slate-900 focus:outline-none" value="db_tabsis" readonly>
                    </div>
                    
                    <div class="space-y-1.5">
                        <label class="text-sm font-medium text-slate-700">Format File</label>
                        <input type="text" class="block w-full rounded-xl border border-slate-300 bg-slate-50 px-4 py-2.5 text-sm text-slate-900 focus:outline-none" value="SQL (MySQL Dump)" readonly>
                    </div>
                    
                    <div class="space-y-1.5">
                        <label class="text-sm font-medium text-slate-700">Lokasi Backup</label>
                        <input type="text" class="block w-full rounded-xl border border-slate-300 bg-slate-50 px-4 py-2.5 text-sm text-slate-900 focus:outline-none" value="backup/" readonly>
                    </div>
                </div>
                <div class="px-6 py-4 bg-slate-50 border-t border-slate-100">
                    <button type="submit" name="backup" class="w-full inline-flex items-center justify-center gap-2 rounded-xl bg-indigo-600 px-4 py-3 text-sm font-medium text-white hover:bg-indigo-700 hover:shadow-lg hover:shadow-indigo-500/30 transition-all">
                        <i class="fa-solid fa-download"></i>
                        <span>Buat Backup Sekarang</span>
                    </button>
                </div>
            </form>
        </div>

        <!-- Restore Card -->
        <div class="rounded-2xl bg-white shadow-sm h-full flex flex-col">
            <div class="border-b border-slate-100 px-6 py-4">
                <h3 class="text-lg font-semibold text-slate-900 flex items-center gap-2">
                    <i class="fa-solid fa-upload text-amber-500"></i>
                    <span>Restore Database</span>
                </h3>
            </div>
            <form method="POST" action="" enctype="multipart/form-data" class="flex-1 flex flex-col">
                <div class="p-6 space-y-4 flex-1">
                    <div class="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">
                        <div class="flex items-start gap-3">
                            <i class="fa-solid fa-triangle-exclamation text-lg text-amber-600"></i>
                            <div>
                                <strong class="text-amber-900">Peringatan:</strong>
                                <span> Restore akan mengganti seluruh data di database dengan data dari file SQL. Pastikan Anda sudah melakukan backup sebelum restore!</span>
                            </div>
                        </div>
                    </div>
                    
                    <div class="space-y-1.5">
                        <label class="text-sm font-medium text-slate-700">Pilih File SQL</label>
                        <input type="file" name="file_restore" class="block w-full rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm text-slate-900 focus:border-amber-500 focus:outline-none focus:ring-2 focus:ring-amber-500/20 file:mr-4 file:py-1 file:px-3 file:rounded-full file:border-0 file:text-xs file:font-bold file:bg-amber-50 file:text-amber-700 hover:file:bg-amber-100" accept=".sql" required>
                        <p class="text-xs text-slate-600 mt-1">Format: File SQL (.sql)</p>
                    </div>
                    
                    <div class="flex items-start gap-3 rounded-xl bg-slate-50 p-4">
                        <div class="h-5 flex items-center">
                            <input type="checkbox" id="confirm_restore" name="confirm_restore" required class="h-4 w-4 rounded border-slate-300 text-amber-600 focus:ring-amber-500">
                        </div>
                        <label for="confirm_restore" class="text-sm text-slate-800 cursor-pointer select-none">
                            Saya mengerti bahwa restore akan mengganti seluruh data database dengan data yang ada di file backup.
                        </label>
                    </div>
                </div>
                <div class="px-6 py-4 bg-slate-50 border-t border-slate-100">
                    <button type="submit" name="restore" class="w-full inline-flex items-center justify-center gap-2 rounded-xl bg-amber-600 px-4 py-3 text-sm font-medium text-white transition-all opacity-50 cursor-not-allowed" id="btn_restore" disabled>
                        <i class="fa-solid fa-upload"></i>
                        <span>Restore Database</span>
                    </button>
                </div>
            </form>
        </div>
    </div>

    <!-- List Backup Files -->
    <div class="rounded-2xl bg-white shadow-sm">
        <div class="border-b border-slate-100 px-6 py-4">
            <h3 class="text-lg font-semibold text-slate-900 flex items-center gap-2">
                <i class="fa-solid fa-list text-indigo-500"></i> Daftar File Backup
            </h3>
        </div>
        <div class="p-6">
            <div class="table-responsive">
                <div class="flex items-center justify-between mb-3">
                    <div class="flex items-center gap-2">
                        <input id="datatableSearch" class="auth-input" placeholder="Cari file backup...">
                        <select id="datatablePageSize" class="auth-input">
                            <option value="10">10</option>
                            <option value="25" selected>25</option>
                            <option value="50">50</option>
                            <option value="100">100</option>
                        </select>
                    </div>
                </div>
                
                <table id="example1" class="w-full table-dashboard text-xs">
                    <thead>
                        <tr>
                            <th class="px-4 py-3 font-medium text-center" width="5%">No</th>
                            <th class="px-4 py-3 font-medium">Nama File</th>
                            <th class="px-4 py-3 font-medium">Ukuran</th>
                            <th class="px-4 py-3 font-medium">Tanggal</th>
                            <th class="px-4 py-3 font-medium text-center" width="20%">Aksi</th>
                        </tr>
                    </thead>
                    <tbody id="datatableUsersBody">
                        <?php
                        $backup_dir = dirname(dirname(__DIR__)) . '/backup/';
                        if (file_exists($backup_dir)) {
                            $files = glob($backup_dir . 'backup_*.sql');
                            rsort($files); // Sort by newest first
                            
                            if (empty($files)) {
                                // Empty state handled by JS or simple row
                            } else {
                                $no = 1;
                                foreach ($files as $file) {
                                    $filename = basename($file);
                                    $filesize = filesize($file);
                                    $filesize_mb = round($filesize / 1024 / 1024, 2);
                                    $filedate = date('Y-m-d H:i:s', filemtime($file));
                                    $filepath = 'backup/' . $filename;
                                    
                                    echo '<tr>';
                                    echo '<td class="text-center font-bold text-slate-800">' . $no++ . '</td>';
                                    echo '<td class="font-bold text-slate-900" style="color: #0f172a !important;"><div class="flex items-center gap-2"><i class="fa-regular fa-file-code text-indigo-600"></i> ' . $filename . '</div></td>';
                                    echo '<td class="font-bold text-slate-700">' . $filesize_mb . ' MB</td>';
                                    echo '<td class="font-bold text-slate-700">' . $filedate . '</td>';
                                    echo '<td class="text-center">';
                                    echo '<div class="flex items-center justify-center gap-2">';
                                    echo '<a href="' . $filepath . '" class="inline-flex h-8 w-8 items-center justify-center rounded-lg bg-emerald-500 text-white shadow-sm transition-all hover:bg-emerald-600 hover:shadow-emerald-500/30" download title="Download Backup"><i class="fa-solid fa-download"></i></a> ';
                                    echo '<a href="?page=MyApp/backup_restore&hapus_backup=' . urlencode($filename) . '" class="inline-flex h-8 w-8 items-center justify-center rounded-lg bg-rose-500 text-white shadow-sm transition-all hover:bg-rose-600 hover:shadow-rose-500/30 btn-hapus" title="Hapus Backup"><i class="fa-solid fa-trash"></i></a>';
                                    echo '</div>';
                                    echo '</td>';
                                    echo '</tr>';
                                }
                            }
                        }
                        ?>
                    </tbody>
                </table>
                
                <div class="mt-3 flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
                    <span id="datatableInfoText" class="text-[11px] text-slate-500"></span>
                    <ul id="datatablePagination" class="pagination"></ul>
                </div>
            </div>
        </div>
    </div>
</section>

<script>
    // Restore Button Logic
    const confirmRestore = document.getElementById('confirm_restore');
    const btnRestore = document.getElementById('btn_restore');

    if (confirmRestore && btnRestore) {
        confirmRestore.addEventListener('change', function() {
            btnRestore.disabled = !this.checked;
            if (this.checked) {
                btnRestore.classList.remove('opacity-50', 'cursor-not-allowed');
                btnRestore.classList.add('hover:bg-amber-700', 'hover:shadow-lg', 'hover:shadow-amber-500/30');
            } else {
                btnRestore.classList.add('opacity-50', 'cursor-not-allowed');
                btnRestore.classList.remove('hover:bg-amber-700', 'hover:shadow-lg', 'hover:shadow-amber-500/30');
            }
        });
    }

    // Delete Confirmation
    document.addEventListener('click', function(e) {
        const deleteBtn = e.target.closest('.btn-hapus');
        if (deleteBtn) {
            e.preventDefault();
            const url = deleteBtn.getAttribute('href');
            
            Swal.fire({
                title: 'Hapus Backup?',
                text: "File backup yang dihapus tidak dapat dikembalikan!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#d33',
                cancelButtonColor: '#3085d6',
                confirmButtonText: 'Ya, Hapus!',
                cancelButtonText: 'Batal'
            }).then((result) => {
                if (result.isConfirmed) {
                    window.location.href = url;
                }
            });
        }
    });
</script>

<style>
.box-primary {
    border-top-color: #3c8dbc;
}

.box-warning {
    border-top-color: #f0ad4e;
}

.box-info {
    border-top-color: #00c0ef;
}

.alert {
    margin-bottom: 20px;
}

.btn-lg {
    padding: 12px 24px;
    font-size: 16px;
}

.box {
    box-shadow: 0 1px 3px rgba(0,0,0,.12), 0 1px 2px rgba(0,0,0,.24);
    border-radius: 4px;
}
</style>

