<?php
include dirname(dirname(__DIR__)) . '/inc/koneksi.php';
include_once dirname(dirname(__DIR__)) . '/inc/activity_log.php';

// Proses Backup
if (isset($_POST['backup'])) {
    $db_name = 'db_tabsis';
    $backup_dir = dirname(dirname(__DIR__)) . '/backup/';
    
    // Buat folder backup jika belum ada
    if (!file_exists($backup_dir)) {
        mkdir($backup_dir, 0777, true);
    }
    
    $filename = 'backup_' . $db_name . '_' . date('Y-m-d_His') . '.sql';
    $filepath = $backup_dir . $filename;
    
    // Koneksi database
    $host = 'localhost';
    $user = 'root';
    $pass = '';
    
    // Command untuk backup menggunakan mysqldump
    $command = "mysqldump --host=$host --user=$user --password=$pass $db_name > " . escapeshellarg($filepath) . " 2>&1";
    
    // Jika di Windows (Laragon)
    if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') {
        // Cari path MySQL di Laragon
        $mysql_paths = [
            'C:\\laragon\\bin\\mysql\\mysql-8.0.30\\bin\\mysqldump.exe',
            'C:\\laragon\\bin\\mysql\\mysql-8.0.24\\bin\\mysqldump.exe',
            'C:\\xampp\\mysql\\bin\\mysqldump.exe',
            'C:\\wamp64\\bin\\mysql\\mysql8.0.27\\bin\\mysqldump.exe',
        ];
        
        $mysqldump = '';
        foreach ($mysql_paths as $path) {
            if (file_exists($path)) {
                $mysqldump = $path;
                break;
            }
        }
        
        if (empty($mysqldump)) {
            // Fallback: coba dari PATH
            $mysqldump = 'mysqldump';
        }
        
        $command = "\"$mysqldump\" --host=$host --user=$user --password=$pass $db_name > " . escapeshellarg($filepath) . " 2>&1";
    }
    
    exec($command, $output, $return_var);
    
    if ($return_var === 0 && file_exists($filepath) && filesize($filepath) > 0) {
        $file_size = filesize($filepath);
        $file_size_mb = round($file_size / 1024 / 1024, 2);
        
            // Log aktivitas
            if (function_exists('logActivity')) {
                logActivity($koneksi, 'BACKUP', 'database', 'Membuat backup database: ' . $filename . ' (' . $file_size_mb . ' MB)');
            }
            
            echo "<script>
            Swal.fire({
                title: 'Backup Berhasil!',
                html: 'Database berhasil di-backup.<br><br><strong>File:</strong> $filename<br><strong>Ukuran:</strong> $file_size_mb MB<br><strong>Lokasi:</strong> backup/$filename',
                icon: 'success',
                confirmButtonText: 'OK'
            });
            </script>";
    } else {
        // Fallback: Backup manual menggunakan PHP (lebih reliable)
        $backup_content = "-- Backup Database: $db_name\n";
        $backup_content .= "-- Tanggal: " . date('Y-m-d H:i:s') . "\n";
        $backup_content .= "-- Generated by PHP Backup Script\n\n";
        $backup_content .= "SET SQL_MODE = \"NO_AUTO_VALUE_ON_ZERO\";\n";
        $backup_content .= "SET time_zone = \"+00:00\";\n";
        $backup_content .= "SET FOREIGN_KEY_CHECKS = 0;\n\n";
        $backup_content .= "CREATE DATABASE IF NOT EXISTS `$db_name` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;\n";
        $backup_content .= "USE `$db_name`;\n\n";
        
        // Get all tables
        $tables = [];
        $result = mysqli_query($koneksi, "SHOW TABLES");
        if ($result) {
            while ($row = mysqli_fetch_row($result)) {
                $tables[] = $row[0];
            }
        }
        
        $total_rows = 0;
        $table_stats = [];
        
        foreach ($tables as $table) {
            $backup_content .= "\n-- --------------------------------------------------------\n";
            $backup_content .= "-- Table structure for table `$table`\n";
            $backup_content .= "-- --------------------------------------------------------\n\n";
            $backup_content .= "DROP TABLE IF EXISTS `$table`;\n";
            
            $create_table = mysqli_query($koneksi, "SHOW CREATE TABLE `$table`");
            if ($create_table && $create_row = mysqli_fetch_row($create_table)) {
                $backup_content .= $create_row[1] . ";\n\n";
            }
            
            // Get table data
            $backup_content .= "-- Dumping data for table `$table`\n\n";
            
            // Count total rows first
            $count_result = mysqli_query($koneksi, "SELECT COUNT(*) as total FROM `$table`");
            $count_data = mysqli_fetch_assoc($count_result);
            $table_row_count = $count_data['total'];
            
            $data_result = mysqli_query($koneksi, "SELECT * FROM `$table`");
            
            if ($data_result && mysqli_num_rows($data_result) > 0) {
                // Get column names
                $columns = [];
                $fields = mysqli_fetch_fields($data_result);
                foreach ($fields as $field) {
                    $columns[] = "`" . $field->name . "`";
                }
                $column_list = implode(", ", $columns);
                
                // Reset result pointer
                mysqli_data_seek($data_result, 0);
                
                $backup_content .= "INSERT INTO `$table` ($column_list) VALUES\n";
                $values = [];
                $row_count = 0;
                
                while ($data_row = mysqli_fetch_assoc($data_result)) {
                    $row_values = [];
                    foreach ($columns as $col) {
                        $col_name = trim($col, '`');
                        $value = isset($data_row[$col_name]) ? $data_row[$col_name] : null;
                        
                        if ($value === null) {
                            $row_values[] = 'NULL';
                        } else {
                            // Escape properly - handle special characters
                            $escaped = mysqli_real_escape_string($koneksi, $value);
                            // Handle binary data or special characters
                            $row_values[] = "'" . str_replace(array("\r", "\n", "\t"), array("\\r", "\\n", "\\t"), $escaped) . "'";
                        }
                    }
                    $values[] = "(" . implode(", ", $row_values) . ")";
                    $row_count++;
                }
                
                if (!empty($values)) {
                    // Split large inserts into chunks for better performance
                    $chunk_size = 100;
                    $chunks = array_chunk($values, $chunk_size);
                    
                    foreach ($chunks as $chunk_index => $chunk) {
                        if ($chunk_index > 0) {
                            $backup_content .= "INSERT INTO `$table` ($column_list) VALUES\n";
                        }
                        $backup_content .= implode(",\n", $chunk);
                        if ($chunk_index < count($chunks) - 1) {
                            $backup_content .= ";\n\n";
                        } else {
                            $backup_content .= ";\n\n";
                        }
                    }
                    
                    $total_rows += $row_count;
                    $table_stats[$table] = $row_count;
                } else {
                    $backup_content .= "-- No data in table `$table`\n\n";
                    $table_stats[$table] = 0;
                }
            } else {
                $backup_content .= "-- No data in table `$table`\n\n";
                $table_stats[$table] = 0;
            }
        }
        
        $backup_content .= "\nSET FOREIGN_KEY_CHECKS = 1;\n";
        
        // Write to file
        $written = file_put_contents($filepath, $backup_content);
        
        if ($written !== false && file_exists($filepath) && filesize($filepath) > 0) {
            $file_size = filesize($filepath);
            $file_size_kb = round($file_size / 1024, 2);
            $file_size_mb = round($file_size / 1024 / 1024, 2);
            
            $size_display = $file_size_mb >= 1 ? $file_size_mb . ' MB' : $file_size_kb . ' KB';
            
            // Build table stats detail
            $stats_detail = '';
            foreach ($table_stats as $tbl => $count) {
                $stats_detail .= '<br>- ' . $tbl . ': ' . $count . ' baris';
            }
            
            // Log aktivitas
            if (function_exists('logActivity')) {
                logActivity($koneksi, 'BACKUP', 'database', 'Membuat backup database: ' . $filename . ' (' . $size_display . ', ' . count($tables) . ' tabel, ' . $total_rows . ' baris)');
            }
            
            echo "<script>
            Swal.fire({
                title: 'Backup Berhasil!',
                html: 'Database berhasil di-backup.<br><br><strong>File:</strong> $filename<br><strong>Ukuran:</strong> $size_display<br><strong>Total Tabel:</strong> " . count($tables) . "<br><strong>Total Data:</strong> $total_rows baris<br><strong>Detail per Tabel:</strong>$stats_detail<br><br><strong>Lokasi:</strong> backup/$filename',
                icon: 'success',
                confirmButtonText: 'OK',
                width: '600px'
            });
            </script>";
        } else {
            $error_msg = 'Gagal membuat file backup.';
            if (!is_writable($backup_dir)) {
                $error_msg .= ' Folder backup tidak dapat ditulis.';
            }
            
            echo "<script>
            Swal.fire({
                title: 'Backup Gagal!',
                text: '$error_msg',
                icon: 'error',
                confirmButtonText: 'OK'
            });
            </script>";
        }
    }
}

// Proses Hapus Backup
if (isset($_GET['hapus_backup'])) {
    $filename = basename($_GET['hapus_backup']);
    $backup_dir = dirname(dirname(__DIR__)) . '/backup/';
    $filepath = $backup_dir . $filename;
    
    // Validasi: hanya file backup yang bisa dihapus
    if (strpos($filename, 'backup_') === 0 && pathinfo($filename, PATHINFO_EXTENSION) === 'sql') {
        if (file_exists($filepath)) {
            if (unlink($filepath)) {
                // Log aktivitas
                if (function_exists('logActivity')) {
                    logActivity($koneksi, 'DELETE', 'backup', 'Menghapus file backup: ' . $filename);
                }
                
                echo "<script>
                Swal.fire({
                    title: '<i class=\"fa fa-check-circle\" style=\"color: #28a745;\"></i> File Berhasil Dihapus!',
                    html: '<div style=\"text-align: center; padding: 10px;\">' +
                          '<p style=\"font-size: 16px; margin-bottom: 15px;\">File backup telah berhasil dihapus:</p>' +
                          '<div style=\"background-color: #f8f9fa; padding: 15px; border-radius: 5px; display: inline-block; margin-bottom: 15px;\">' +
                          '<p style=\"margin: 0; font-weight: bold; color: #495057;\"><i class=\"fa fa-file-code-o\"></i> ' + " . json_encode($filename) . " + '</p>' +
                          '</div>' +
                          '</div>',
                    icon: 'success',
                    confirmButtonColor: '#28a745',
                    confirmButtonText: '<i class=\"fa fa-check\"></i> OK',
                    timer: 3000,
                    timerProgressBar: true
                }).then((result) => {
                    window.location = 'index.php?page=MyApp/backup_restore';
                });
                </script>";
            } else {
                echo "<script>
                Swal.fire({
                    title: 'Gagal Menghapus',
                    text: 'Gagal menghapus file backup',
                    icon: 'error',
                    confirmButtonText: 'OK'
                });
                </script>";
            }
        } else {
            echo "<script>
            Swal.fire({
                title: 'File Tidak Ditemukan',
                text: 'File backup tidak ditemukan',
                icon: 'error',
                confirmButtonText: 'OK'
            });
            </script>";
        }
    } else {
        echo "<script>
        Swal.fire({
            title: 'Akses Ditolak',
            text: 'File tidak valid untuk dihapus',
            icon: 'error',
            confirmButtonText: 'OK'
        });
        </script>";
    }
}

// Proses Restore
if (isset($_POST['restore'])) {
    if (isset($_FILES['file_restore']) && $_FILES['file_restore']['error'] == 0) {
        $file_tmp = $_FILES['file_restore']['tmp_name'];
        $file_name = $_FILES['file_restore']['name'];
        $file_ext = strtolower(pathinfo($file_name, PATHINFO_EXTENSION));
        
        if ($file_ext !== 'sql') {
            echo "<script>
            Swal.fire({
                title: 'Format File Tidak Valid',
                text: 'Hanya file SQL yang diperbolehkan',
                icon: 'error',
                confirmButtonText: 'OK'
            });
            </script>";
        } else {
            // Baca file SQL
            $sql_content = file_get_contents($file_tmp);
            
            if (empty($sql_content)) {
                echo "<script>
                Swal.fire({
                    title: 'File Kosong',
                    text: 'File SQL yang diupload kosong atau tidak valid',
                    icon: 'error',
                    confirmButtonText: 'OK'
                });
                </script>";
            } else {
                // Set timeout untuk query besar
                set_time_limit(300);
                ini_set('max_execution_time', 300);
                ini_set('memory_limit', '256M');
                
                // Disable foreign key checks
                mysqli_query($koneksi, "SET FOREIGN_KEY_CHECKS = 0");
                mysqli_query($koneksi, "SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO'");
                
                $success_count = 0;
                $error_count = 0;
                $errors = [];
                
                // Baca file baris per baris dan eksekusi query
                $handle = fopen($file_tmp, 'r');
                if ($handle) {
                    $current_query = '';
                    
                    while (($line = fgets($handle)) !== false) {
                        $line = trim($line);
                        
                        // Skip komentar dan baris kosong
                        if (empty($line) || 
                            strpos($line, '--') === 0 || 
                            strpos($line, '/*') === 0 ||
                            strpos($line, '*/') !== false) {
                            continue;
                        }
                        
                        // Hapus komentar di akhir baris
                        if (strpos($line, '--') !== false) {
                            $line = substr($line, 0, strpos($line, '--'));
                            $line = trim($line);
                        }
                        
                        // Tambahkan baris ke query
                        $current_query .= $line . ' ';
                        
                        // Jika baris berakhir dengan semicolon, eksekusi query
                        if (substr(rtrim($line), -1) === ';') {
                            $query = trim($current_query);
                            $current_query = '';
                            
                            // Skip query kosong atau terlalu pendek
                            if (empty($query) || strlen($query) < 5) {
                                continue;
                            }
                            
                            // Skip CREATE DATABASE dan USE (sudah di database yang benar)
                            if (preg_match('/^(CREATE DATABASE|USE|SET)/i', trim($query))) {
                                // Execute SET commands
                                if (preg_match('/^SET/i', trim($query))) {
                                    mysqli_query($koneksi, $query);
                                }
                                continue;
                            }
                            
                            // Eksekusi query
                            if (mysqli_query($koneksi, $query)) {
                                $success_count++;
                            } else {
                                $error = mysqli_error($koneksi);
                                // Skip error yang tidak kritis
                                if (strpos($error, 'Duplicate entry') === false && 
                                    strpos($error, 'already exists') === false &&
                                    strpos($error, 'Unknown database') === false &&
                                    strpos($error, 'Table') === false) {
                                    $error_count++;
                                    if (count($errors) < 10) {
                                        $errors[] = substr($error, 0, 100);
                                    }
                                } else {
                                    $success_count++; // Count as success
                                }
                            }
                        }
                    }
                    fclose($handle);
                } else {
                    $error_count++;
                    $errors[] = 'Gagal membaca file SQL';
                }
                
                // Enable foreign key checks
                mysqli_query($koneksi, "SET FOREIGN_KEY_CHECKS = 1");
                
                // Count data yang ter-restore
                $affected_rows = 0;
                $tables_restored = [];
                $result = mysqli_query($koneksi, "SHOW TABLES");
                if ($result) {
                    while ($row = mysqli_fetch_row($result)) {
                        $table = $row[0];
                        $count_result = mysqli_query($koneksi, "SELECT COUNT(*) as total FROM `$table`");
                        if ($count_result) {
                            $count_data = mysqli_fetch_assoc($count_result);
                            $tables_restored[$table] = $count_data['total'];
                            $affected_rows += $count_data['total'];
                        }
                    }
                }
                
                if ($error_count == 0) {
                    $tables_detail = '';
                    foreach ($tables_restored as $tbl => $count) {
                        $tables_detail .= '<br>- ' . $tbl . ': ' . $count . ' baris';
                    }
                    
                    // Log aktivitas
                    if (function_exists('logActivity')) {
                        logActivity($koneksi, 'RESTORE', 'database', 'Restore database dari file: ' . $file_name . ' (' . $success_count . ' query berhasil, ' . $affected_rows . ' baris)');
                    }
                    
                    echo "<script>
                    Swal.fire({
                        title: 'Restore Berhasil!',
                        html: 'Database berhasil di-restore.<br><br><strong>Query berhasil:</strong> $success_count<br><strong>Total Data:</strong> $affected_rows baris<br><strong>Detail per Tabel:</strong>$tables_detail',
                        icon: 'success',
                        confirmButtonText: 'OK',
                        width: '600px'
                    }).then((result) => {
                        if (result.value) {
                            window.location = 'index.php?page=MyApp/backup_restore';
                        }
                    });
                    </script>";
                } else {
                    $error_msg = implode('<br>', array_slice($errors, 0, 10));
                    if (count($errors) > 10) {
                        $error_msg .= '<br>... dan ' . (count($errors) - 10) . ' error lainnya';
                    }
                    
                    $tables_detail = '';
                    if (!empty($tables_restored)) {
                        foreach ($tables_restored as $tbl => $count) {
                            $tables_detail .= '<br>- ' . $tbl . ': ' . $count . ' baris';
                        }
                    }
                    
                    echo "<script>
                    Swal.fire({
                        title: 'Restore dengan Error',
                        html: 'Database di-restore dengan beberapa error.<br><br><strong>Query berhasil:</strong> $success_count<br><strong>Query gagal:</strong> $error_count<br><strong>Data ter-restore:</strong> $affected_rows baris$tables_detail<br><br><strong>Detail Error:</strong><br>$error_msg',
                        icon: 'warning',
                        confirmButtonText: 'OK',
                        width: '700px'
                    });
                    </script>";
                }
            }
        }
    } else {
        echo "<script>
        Swal.fire({
            title: 'File Tidak Ditemukan',
            text: 'Silakan pilih file SQL untuk di-restore',
            icon: 'error',
            confirmButtonText: 'OK'
        });
        </script>";
    }
}
?>

<section class="content-header">
    <h1>
        Backup & Restore Database
        <small>Kelola backup dan restore database</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="?page=admin"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Backup & Restore</li>
    </ol>
</section>

<section class="content">
    <div class="row">
        <!-- Backup Card -->
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">
                        <i class="fa fa-download"></i> Backup Database
                    </h3>
                </div>
                <form method="POST" action="">
                    <div class="box-body">
                        <div class="alert alert-info">
                            <i class="fa fa-info-circle"></i> 
                            <strong>Informasi:</strong> Backup akan membuat file SQL dari seluruh database. 
                            File akan disimpan di folder <code>backup/</code>
                        </div>
                        
                        <div class="form-group">
                            <label>Nama Database</label>
                            <input type="text" class="form-control" value="db_tabsis" readonly>
                        </div>
                        
                        <div class="form-group">
                            <label>Format File</label>
                            <input type="text" class="form-control" value="SQL (MySQL Dump)" readonly>
                        </div>
                        
                        <div class="form-group">
                            <label>Lokasi Backup</label>
                            <input type="text" class="form-control" value="backup/" readonly>
                        </div>
                    </div>
                    <div class="box-footer">
                        <button type="submit" name="backup" class="btn btn-primary btn-lg btn-block">
                            <i class="fa fa-download"></i> Buat Backup Sekarang
                        </button>
                    </div>
                </form>
            </div>
        </div>

        <!-- Restore Card -->
        <div class="col-md-6">
            <div class="box box-warning">
                <div class="box-header with-border">
                    <h3 class="box-title">
                        <i class="fa fa-upload"></i> Restore Database
                    </h3>
                </div>
                <form method="POST" action="" enctype="multipart/form-data">
                    <div class="box-body">
                        <div class="alert alert-warning">
                            <i class="fa fa-exclamation-triangle"></i> 
                            <strong>Peringatan:</strong> Restore akan mengganti seluruh data di database dengan data dari file SQL. 
                            Pastikan Anda sudah melakukan backup sebelum restore!
                        </div>
                        
                        <div class="form-group">
                            <label>Pilih File SQL</label>
                            <input type="file" name="file_restore" class="form-control" accept=".sql" required>
                            <small class="help-block">Format: File SQL (.sql)</small>
                        </div>
                        
                        <div class="form-group">
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" id="confirm_restore" name="confirm_restore" required 
                                           onchange="document.getElementById('btn_restore').disabled = !this.checked; 
                                                    if(this.checked) {
                                                        document.getElementById('btn_restore').style.opacity = '1';
                                                        document.getElementById('btn_restore').style.cursor = 'pointer';
                                                    } else {
                                                        document.getElementById('btn_restore').style.opacity = '0.6';
                                                        document.getElementById('btn_restore').style.cursor = 'not-allowed';
                                                    }">
                                    Saya mengerti bahwa restore akan mengganti seluruh data database
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        <button type="submit" name="restore" class="btn btn-warning btn-lg btn-block" id="btn_restore" disabled style="opacity: 0.6; cursor: not-allowed;">
                            <i class="fa fa-upload"></i> Restore Database
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- List Backup Files -->
    <div class="row">
        <div class="col-md-12">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">
                        <i class="fa fa-list"></i> Daftar File Backup
                    </h3>
                </div>
                <div class="box-body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped table-hover" id="table-backup">
                            <thead>
                                <tr>
                                    <th style="width: 5%;">No</th>
                                    <th style="width: 40%;">Nama File</th>
                                    <th style="width: 15%;">Ukuran</th>
                                    <th style="width: 20%;">Tanggal</th>
                                    <th style="width: 20%; text-align: center;">Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $backup_dir = dirname(dirname(__DIR__)) . '/backup/';
                                if (file_exists($backup_dir)) {
                                    $files = glob($backup_dir . 'backup_*.sql');
                                    rsort($files); // Sort by newest first
                                    
                                    if (empty($files)) {
                                        echo '<tr><td colspan="5" class="text-center">Tidak ada file backup</td></tr>';
                                    } else {
                                        $no = 1;
                                        foreach ($files as $file) {
                                            $filename = basename($file);
                                            $filesize = filesize($file);
                                            $filesize_mb = round($filesize / 1024 / 1024, 2);
                                            $filedate = date('Y-m-d H:i:s', filemtime($file));
                                            $filepath = '../backup/' . $filename;
                                            
                                            echo '<tr>';
                                            echo '<td>' . $no++ . '</td>';
                                            echo '<td><i class="fa fa-file-code-o"></i> ' . $filename . '</td>';
                                            echo '<td>' . $filesize_mb . ' MB</td>';
                                            echo '<td>' . $filedate . '</td>';
                                            echo '<td class="text-center">';
                                            echo '<a href="' . $filepath . '" class="btn btn-sm btn-success" download><i class="fa fa-download"></i> Download</a> ';
                                            echo '<button type="button" class="btn btn-sm btn-danger btn-hapus-backup" onclick="hapusBackupFile(\'' . htmlspecialchars($filename, ENT_QUOTES) . '\', \'' . $filesize_mb . '\', \'' . $filedate . '\', \'?page=MyApp/backup_restore&hapus_backup=' . urlencode($filename) . '\')" data-file="' . htmlspecialchars($filename) . '" data-size="' . $filesize_mb . '" data-date="' . $filedate . '" data-url="?page=MyApp/backup_restore&hapus_backup=' . urlencode($filename) . '"><i class="fa fa-trash"></i> Hapus</button>';
                                            echo '</td>';
                                            echo '</tr>';
                                        }
                                    }
                                } else {
                                    echo '<tr><td colspan="5" class="text-center">Folder backup belum dibuat</td></tr>';
                                }
                                ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script>
// Fungsi global untuk hapus backup (fallback jika jQuery tidak bekerja)
function hapusBackupFile(filename, filesize, filedate, deleteUrl) {
    if (typeof Swal !== 'undefined') {
        Swal.fire({
            title: '<i class="fa fa-exclamation-triangle" style="color: #f39c12; font-size: 48px;"></i>',
            html: '<div style="text-align: center; padding: 10px;">' +
                  '<h3 style="color: #d33; margin-bottom: 20px; font-weight: bold;">Konfirmasi Hapus File Backup</h3>' +
                  '<p style="font-size: 16px; margin-bottom: 20px; color: #495057;">Anda yakin ingin menghapus file backup berikut?</p>' +
                  '<div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; border-radius: 10px; margin-bottom: 20px; text-align: left;">' +
                  '<p style="margin: 8px 0; font-size: 15px;"><i class="fa fa-file-code-o" style="margin-right: 8px;"></i><strong>Nama File:</strong><br><span style="font-family: monospace; background: rgba(255,255,255,0.2); padding: 5px 10px; border-radius: 5px; display: inline-block; margin-top: 5px;">' + filename + '</span></p>' +
                  '<p style="margin: 8px 0; font-size: 15px;"><i class="fa fa-hdd-o" style="margin-right: 8px;"></i><strong>Ukuran:</strong> ' + filesize + ' MB</p>' +
                  '<p style="margin: 8px 0; font-size: 15px;"><i class="fa fa-calendar" style="margin-right: 8px;"></i><strong>Tanggal:</strong> ' + filedate + '</p>' +
                  '</div>' +
                  '<div style="background-color: #fff3cd; border: 2px solid #ffc107; border-radius: 8px; padding: 15px; margin-top: 15px;">' +
                  '<p style="margin: 0; color: #856404; font-size: 14px; font-weight: bold;">' +
                  '<i class="fa fa-warning" style="margin-right: 8px;"></i>' +
                  'PERINGATAN: File yang dihapus tidak dapat dikembalikan!</p>' +
                  '</div>' +
                  '</div>',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#d33',
            cancelButtonColor: '#6c757d',
            confirmButtonText: '<i class="fa fa-trash"></i> Ya, Hapus Sekarang!',
            cancelButtonText: '<i class="fa fa-times"></i> Batal',
            reverseButtons: true,
            focusCancel: true,
            allowOutsideClick: false,
            allowEscapeKey: true,
            width: '650px',
            customClass: {
                popup: 'animated fadeIn'
            },
            buttonsStyling: true
        }).then((result) => {
            if (result.isConfirmed === true) {
                Swal.fire({
                    title: 'Sedang Menghapus...',
                    html: '<div style="padding: 20px;">' +
                          '<i class="fa fa-spinner fa-spin fa-3x" style="color: #d33; margin-bottom: 15px;"></i>' +
                          '<p style="font-size: 16px; margin-top: 15px;">Menghapus file: <strong>' + filename + '</strong></p>' +
                          '<p style="font-size: 14px; color: #6c757d;">Mohon tunggu...</p>' +
                          '</div>',
                    allowOutsideClick: false,
                    allowEscapeKey: false,
                    showConfirmButton: false,
                    didOpen: () => {
                        Swal.showLoading();
                    }
                });
                
                setTimeout(function() {
                    window.location.href = deleteUrl;
                }, 500);
            } else {
                Swal.fire({
                    title: 'Dibatalkan',
                    text: 'File backup tidak dihapus',
                    icon: 'info',
                    confirmButtonColor: '#3085d6',
                    confirmButtonText: 'OK',
                    timer: 2000,
                    timerProgressBar: true
                });
            }
        });
    } else {
        // Fallback jika SweetAlert tidak tersedia
        Swal.fire({
            title: 'Error',
            text: 'SweetAlert tidak tersedia. Silakan refresh halaman.',
            icon: 'error',
            confirmButtonText: 'OK'
        });
    }
}

// Pastikan jQuery dan SweetAlert tersedia
// (Silent check - tidak ada logging)

// Semua script dalam satu document.ready
$(document).ready(function() {
    // Enable/disable restore button
    var checkbox = $('#confirm_restore');
    var button = $('#btn_restore');
    
    // Function to update button
    function updateButton() {
        var isChecked = checkbox.is(':checked');
        button.prop('disabled', !isChecked);
        
        if (isChecked) {
            button.css({
                'opacity': '1',
                'cursor': 'pointer'
            }).removeClass('disabled');
        } else {
            button.css({
                'opacity': '0.6',
                'cursor': 'not-allowed'
            }).addClass('disabled');
        }
    }
    
    // Event handler untuk checkbox restore
    checkbox.on('change click', function() {
        updateButton();
    });
    
    // Initial state
    updateButton();
    
    // Fallback dengan vanilla JS juga untuk checkbox
    var checkboxEl = document.getElementById('confirm_restore');
    var buttonEl = document.getElementById('btn_restore');
    
    if (checkboxEl && buttonEl) {
        checkboxEl.addEventListener('change', function() {
            buttonEl.disabled = !this.checked;
            if (this.checked) {
                buttonEl.style.opacity = '1';
                buttonEl.style.cursor = 'pointer';
            } else {
                buttonEl.style.opacity = '0.6';
                buttonEl.style.cursor = 'not-allowed';
            }
        });
    }
    
    // Hapus backup file - dengan alert konfirmasi WAJIB
    // Gunakan event delegation untuk memastikan handler terpasang
    $(document).on('click', '.btn-hapus-backup', function(e) {
        e.preventDefault();
        e.stopPropagation();
        
        var $btn = $(this);
        var filename = $btn.data('file');
        var filesize = $btn.data('size') || 'N/A';
        var filedate = $btn.data('date') || 'N/A';
        var deleteUrl = $btn.data('url');
        
        // Validasi data
        if (!filename || !deleteUrl) {
            if (typeof Swal !== 'undefined') {
                Swal.fire({
                    title: 'Error',
                    text: 'Data tidak lengkap',
                    icon: 'error'
                });
            } else {
                Swal.fire({
                    title: 'Data Tidak Lengkap',
                    text: 'Silakan lengkapi semua data yang diperlukan',
                    icon: 'warning',
                    confirmButtonText: 'OK'
                });
            }
            return false;
        }
        
        // Alert konfirmasi WAJIB sebelum menghapus
        if (typeof Swal !== 'undefined') {
            Swal.fire({
                title: '<i class="fa fa-exclamation-triangle" style="color: #f39c12; font-size: 48px;"></i>',
                html: '<div style="text-align: center; padding: 10px;">' +
                      '<h3 style="color: #d33; margin-bottom: 20px; font-weight: bold;">Konfirmasi Hapus File Backup</h3>' +
                      '<p style="font-size: 16px; margin-bottom: 20px; color: #495057;">Anda yakin ingin menghapus file backup berikut?</p>' +
                      '<div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; border-radius: 10px; margin-bottom: 20px; text-align: left;">' +
                      '<p style="margin: 8px 0; font-size: 15px;"><i class="fa fa-file-code-o" style="margin-right: 8px;"></i><strong>Nama File:</strong><br><span style="font-family: monospace; background: rgba(255,255,255,0.2); padding: 5px 10px; border-radius: 5px; display: inline-block; margin-top: 5px;">' + filename + '</span></p>' +
                      '<p style="margin: 8px 0; font-size: 15px;"><i class="fa fa-hdd-o" style="margin-right: 8px;"></i><strong>Ukuran:</strong> ' + filesize + ' MB</p>' +
                      '<p style="margin: 8px 0; font-size: 15px;"><i class="fa fa-calendar" style="margin-right: 8px;"></i><strong>Tanggal:</strong> ' + filedate + '</p>' +
                      '</div>' +
                      '<div style="background-color: #fff3cd; border: 2px solid #ffc107; border-radius: 8px; padding: 15px; margin-top: 15px;">' +
                      '<p style="margin: 0; color: #856404; font-size: 14px; font-weight: bold;">' +
                      '<i class="fa fa-warning" style="margin-right: 8px;"></i>' +
                      'PERINGATAN: File yang dihapus tidak dapat dikembalikan!</p>' +
                      '</div>' +
                      '</div>',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#d33',
                cancelButtonColor: '#6c757d',
                confirmButtonText: '<i class="fa fa-trash"></i> Ya, Hapus Sekarang!',
                cancelButtonText: '<i class="fa fa-times"></i> Batal',
                reverseButtons: true,
                focusCancel: true,
                allowOutsideClick: false,
                allowEscapeKey: true,
                width: '650px',
                customClass: {
                    popup: 'animated fadeIn'
                },
                buttonsStyling: true
            }).then((result) => {
                // HANYA hapus jika user mengkonfirmasi dengan jelas
                if (result.isConfirmed === true) {
                    // Show loading indicator
                    Swal.fire({
                        title: 'Sedang Menghapus...',
                        html: '<div style="padding: 20px;">' +
                              '<i class="fa fa-spinner fa-spin fa-3x" style="color: #d33; margin-bottom: 15px;"></i>' +
                              '<p style="font-size: 16px; margin-top: 15px;">Menghapus file: <strong>' + filename + '</strong></p>' +
                              '<p style="font-size: 14px; color: #6c757d;">Mohon tunggu...</p>' +
                              '</div>',
                        allowOutsideClick: false,
                        allowEscapeKey: false,
                        showConfirmButton: false,
                        didOpen: () => {
                            Swal.showLoading();
                        }
                    });
                    
                    // Redirect ke URL hapus HANYA setelah konfirmasi
                    setTimeout(function() {
                        window.location.href = deleteUrl;
                    }, 500);
                } else {
                    // User membatalkan atau menutup dialog
                    Swal.fire({
                        title: 'Dibatalkan',
                        text: 'File backup tidak dihapus',
                        icon: 'info',
                        confirmButtonColor: '#3085d6',
                        confirmButtonText: 'OK',
                        timer: 2000,
                        timerProgressBar: true
                    });
                }
            });
        } else {
            // Fallback jika SweetAlert tidak tersedia - gunakan alert biasa
            Swal.fire({
                title: 'Error',
                text: 'SweetAlert tidak tersedia. Silakan refresh halaman.',
                icon: 'error',
                confirmButtonText: 'OK'
            });
        }
        
        return false;
    });
});
</script>

<style>
.box-primary {
    border-top-color: #3c8dbc;
}

.box-warning {
    border-top-color: #f0ad4e;
}

.box-info {
    border-top-color: #00c0ef;
}

.alert {
    margin-bottom: 20px;
}

.btn-lg {
    padding: 12px 24px;
    font-size: 16px;
}

.box {
    box-shadow: 0 1px 3px rgba(0,0,0,.12), 0 1px 2px rgba(0,0,0,.24);
    border-radius: 4px;
}
</style>

